# fly.use
# rank.set
# commandblocker.override
# spawn.set

Settings:
  blocked_commands:
    - me
    - minecraft:me
    - say
    - minecraft:say
    - tell
    - minecraft:tell
    - calc
    - calculate
    - eval
    - evaluate
